version: "3"
services:
  mysql:
    image: mysql
    cap_add:
      - SYS_NICE
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ../_volumes/mysql/data:/var/lib/mysql
      - ../_volumes/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: teste123
      MYSQL_DATABASE: mydb
  
  node:
    image: node:16-alpine
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    links:
      - "mysql:mysql"
    command: "yarn dev"